remote_theme: humzak711/hackerv2@master
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Humzak711
description: My blog :)
header_pages:
- index.md
style: dark
